# Generated by Django 4.2.13 on 2024-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_slug_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='\n        Идентификатор страницы для URL; разрешены символы латиницы, цифры, \n        дефис и подчёркивание.\n        ', unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='\n        Если установить дату и время в будущем — \n        можно делать отложенные публикации.\n        ', verbose_name='Дата и время публикации'),
        ),
    ]
