# Generated by Django 4.2.13 on 2024-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_category_slug_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='\nИдентификатор страницы для URL; разрешены символы латиницы, цифры,\nдефис и подчёркивание.\n', unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(help_text='\nЕсли установить дату и время в будущем —\nможно делать отложенные публикации.\n', verbose_name='Дата и время публикации'),
        ),
    ]
