# Generated by Django 3.2.16 on 2024-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_category_slug_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='Планета Земля', max_length=256, verbose_name='Название места'),
        ),
    ]
